"""Workboard test battery. Runs the REAL Worker locally on SQLite, seeds it, then drives the page through its
real controls with Playwright and checks the store received every change. Run: Test.cmd, or
python tests/battery.py   (set WORKBOARD_URL and WORKBOARD_KEY to test a live instance instead)."""
from playwright.sync_api import sync_playwright
import json
import os,subprocess,time,sys,urllib.request
R=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
F=os.environ.get("WORKBOARD_URL","http://localhost:8797/")
KEY=os.environ.get("WORKBOARD_KEY","local")
srv=None
if "localhost:8797" in F:
    subprocess.check_call([sys.executable,os.path.join(R,"scripts/build.py")])  # test what ships: rebuild first
    srv=subprocess.Popen(["node",os.path.join(R,"tests/local_server.mjs"),"8797"],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL); time.sleep(1.5)
    subprocess.check_call([sys.executable,os.path.join(R,"scripts/seed.py"),"--url",F,"--key",KEY,"--file",os.path.join(R,"scripts/seed/brainstorm-2026-09-22.json")])
os.makedirs(os.path.join(R,"tests/shots"),exist_ok=True)
def drag(pg,src,dst):
    a=src.bounding_box(); b=dst.bounding_box()
    pg.mouse.move(a["x"]+15,a["y"]+10); pg.mouse.down()
    for k in range(1,13): pg.mouse.move(a["x"]+15+(b["x"]+25-a["x"]-15)*k/12, a["y"]+10+(b["y"]+25-a["y"]-10)*k/12)
    pg.mouse.up(); pg.wait_for_timeout(80)
res=[]
def ok(name,cond): res.append((name,bool(cond))); print(("PASS " if cond else "FAIL ")+name, flush=True)
with sync_playwright() as p:
    b=p.chromium.launch(); pg=b.new_page(viewport={"width":1440,"height":950})
    errs=[]; pg.on("pageerror",lambda e: errs.append(str(e)))
    pg.route("**/*", lambda r: r.abort() if "fonts" in r.request.url else r.continue_())
    pg.set_default_timeout(8000)
    pg.goto(F); pg.wait_for_timeout(300)
    pg.evaluate("localStorage.clear()"); pg.reload(); pg.wait_for_timeout(300)
    ok("asks for key", pg.locator(".keybox").count()==1)
    pg.locator(".keybox input").fill(KEY); pg.keyboard.press("Enter"); pg.wait_for_timeout(600)
    ok("board 6 cols", pg.locator(".col").count()==6)
    ok("50 cards", pg.locator(".card").count()==50)
    # drag first idea card to Doing
    doing=pg.locator(".colb").nth(4); before=doing.locator(".card").count()
    drag(pg,pg.locator(".colb").nth(0).locator(".card").first,doing)
    pg.wait_for_timeout(700)
    ok("drag to Doing", pg.locator(".colb").nth(4).locator(".card").count()==before+1)
    pg.screenshot(path=os.path.join(R,"tests/shots/")+"board.png"); pg.wait_for_timeout(450)
    # open drawer, set owner via select, post update
    pg.locator(".colb").nth(4).locator(".card").first.click(); pg.wait_for_timeout(100)
    ok("drawer open", pg.locator(".drawer").count()==1)
    t=pg.locator(".drawer .dh span").inner_text()
    pg.locator(".drawer .f select").nth(1).select_option(label="Rick Uher")
    pg.locator(".drawer .f input[type=date]").nth(1).fill("2026-09-01"); pg.locator(".drawer .f input[type=date]").nth(1).dispatch_event("change")
    pg.locator(".drawer .post input").fill("Talked to Rick"); pg.locator(".drawer .post button").click()
    log=pg.locator(".drawer .log").inner_text()
    ok("log has update+owner change", "Talked to Rick" in log and "Owner: none → Rick Uher" in log)
    pg.screenshot(path=os.path.join(R,"tests/shots/")+"drawer.png")
    pg.keyboard.press("Escape")
    ok("overdue count", "1 overdue" in pg.locator(".attn").inner_text())
    pg.wait_for_timeout(700); pg.reload(); pg.wait_for_timeout(700)
    ok("persist after reload", "1 overdue" in pg.locator(".attn").inner_text())
    for v in ["list","matrix","buckets","mine","review","setup"]:
        pg.locator('.tabs button[data-v="%s"]'%v).click(); pg.wait_for_timeout(100); pg.screenshot(path=os.path.join(R,"tests/shots/")+v+".png",full_page=False)
        ok("view "+v, pg.locator("main").inner_text().strip()!="")
    # me = Rick -> my actions shows item
    pg.locator(".top select").nth(1).select_option(label="Rick Uher"); pg.locator('.tabs button[data-v="mine"]').click()
    ok("my actions overdue", "Overdue" in pg.locator("main").inner_text())
    pg.screenshot(path=os.path.join(R,"tests/shots/")+"mine.png")
    # matrix drag
    pg.locator('.tabs button[data-v="matrix"]').click(); pg.wait_for_timeout(100)
    drag(pg,pg.locator(".tray .card").first,pg.locator(".cell").first)
    ok("matrix drag", pg.locator(".cell").first.locator(".card").count()>=1)
    # setup add workstream
    pg.locator('.tabs button[data-v="setup"]').click()
    pg.locator(".setup .sec").nth(1).locator("input[type=text]").last.fill("Leak testing"); pg.locator(".setup .sec").nth(1).locator("button").click()
    ok("ws added", pg.locator(".setup .sec").nth(1).locator(".srow").count()==9)
    # toggles in drawer
    pg.locator('.tabs button[data-v="board"]').click(); pg.wait_for_timeout(450); pg.locator(".colb").nth(0).locator(".card").first.click(); pg.wait_for_timeout(80); print("drawers",pg.locator(".drawer").count())
    pg.locator(".drawer .seg").nth(0).locator("button").nth(0).click()
    pg.locator(".drawer .seg").nth(1).locator("button").nth(2).click()
    ok("impact H pressed", pg.locator(".drawer .seg").nth(0).locator("button").nth(0).get_attribute("aria-pressed")=="true")
    ok("effort L pressed", pg.locator(".drawer .seg").nth(1).locator("button").nth(2).get_attribute("aria-pressed")=="true")
    ok("impact M not pressed", pg.locator(".drawer .seg").nth(0).locator("button").nth(1).get_attribute("aria-pressed")=="false")
    ok("stage pill pressed", pg.locator('.drawer .pills button[aria-pressed="true"]').count()==1)
    ok("priority auto Do first", "Do first" in pg.locator(".drawer select.prisel").evaluate("e=>e.options[e.selectedIndex].text"))
    col=pg.locator(".drawer .seg").nth(0).evaluate("e=>getComputedStyle(e.querySelector('[aria-pressed=true]')).backgroundColor")
    ok("pressed looks different", col not in ("rgb(255, 255, 255)","rgba(0, 0, 0, 0)"))
    pg.screenshot(path=os.path.join(R,"tests/shots/")+"drawer2.png")
    pg.keyboard.press("Escape"); pg.wait_for_timeout(700); pg.reload(); pg.wait_for_timeout(700)
    pg.locator(".colb").nth(0).locator(".card").first.click(); pg.wait_for_timeout(80)
    ok("toggle persists reload", pg.locator(".drawer .seg").nth(0).locator("button").nth(0).get_attribute("aria-pressed")=="true")
    pg.keyboard.press("Escape")
    # buckets sticky + collapse
    pg.locator('.tabs button[data-v="buckets"]').click(); pg.wait_for_timeout(100)
    sc=pg.locator(".bscroll")
    ok("bucket horizontal overflow", sc.evaluate("e=>e.scrollWidth>e.clientWidth"))
    top0=pg.locator(".bch").first.bounding_box()["y"]
    sc.evaluate("e=>{e.scrollTop=600;e.scrollLeft=500}"); pg.wait_for_timeout(50)
    ok("col header sticky", abs(pg.locator(".bch").nth(3).bounding_box()["y"]-top0)<2)
    ok("row header sticky", abs(pg.locator(".brh").nth(2).bounding_box()["x"]-sc.bounding_box()["x"])<12)
    pg.screenshot(path=os.path.join(R,"tests/shots/")+"buckets2.png")
    sc.evaluate("e=>{e.scrollTop=0;e.scrollLeft=0}")
    n0=pg.locator(".bk .card").count(); pg.locator(".brh").first.click()
    ok("row collapses", pg.locator(".bk .card").count()<n0 and pg.locator(".brh").first.get_attribute("aria-expanded")=="false")
    pg.wait_for_timeout(700); pg.reload(); pg.wait_for_timeout(700)
    ok("collapse persists", pg.locator(".brh").first.get_attribute("aria-expanded")=="false")
    pg.locator("text=Collapse all rows").click(); ok("collapse all", pg.locator(".bk .card").count()==0)
    pg.locator("text=Expand all").click(); ok("expand all", pg.locator(".bk .card").count()>0)
    # merge
    pg.locator('.tabs button[data-v="list"]').click()
    pg.locator(".lrow .tt").filter(has_text="Change out the cylinders").first.click()
    pg.locator(".drawer .df select").select_option(index=12)
    ok("merged", pg.locator(".drawer .log").inner_text().count("Merged")>=1)
    pg.keyboard.press("Escape")
    # blocked / checklist / bundle / start via UI
    pg.locator('.tabs button[data-v="board"]').click(); pg.wait_for_timeout(450)
    pg.locator(".colb").nth(3).locator(".card").first.click(); pg.wait_for_timeout(80)
    pg.locator(".drawer .blkh input").check(); pg.wait_for_timeout(50)
    pg.locator('.drawer input[list="reasons"]').fill("Needs 4 hr downtime"); pg.locator('.drawer input[list="reasons"]').dispatch_event("change")
    pg.locator(".drawer .blkbox select").select_option(index=12)
    pg.locator(".drawer .chkadd input").fill("Parts"); pg.keyboard.press("Enter")
    ok("checklist focus kept", pg.evaluate("document.activeElement.closest('.chkadd')!=null"))
    pg.keyboard.type("Program"); pg.keyboard.press("Enter")
    pg.locator(".drawer .ci input[type=checkbox]").first.check()
    ok("checklist 1 of 2", "1 of 2 done" in pg.locator(".drawer").inner_text())
    bsel=pg.locator(".drawer .f").filter(has_text="Bundle").locator("select"); bsel.select_option("_new")
    pg.locator('.drawer input[aria-label="New bundle name"]').fill("Carousel downtime"); pg.locator('.drawer input[aria-label="Bundle date"]').fill("2026-10-01"); pg.locator(".drawer .f").filter(has_text="Bundle").locator("button").click()
    sd=pg.locator(".drawer .f").filter(has_text="Start").locator("input"); sd.fill("2026-09-24"); sd.dispatch_event("change")
    dd=pg.locator(".drawer .f").filter(has_text="Due").locator("input"); dd.fill("2026-10-08"); dd.dispatch_event("change")
    lg=pg.locator(".drawer .log").inner_text()
    ok("log blocked+bundle+checklist", "Blocked: no → yes" in lg and "Bundle: none → Carousel downtime" in lg and "Checklist" in lg and "Start: none" in lg)
    pg.screenshot(path=os.path.join(R,"tests/shots/")+"drawer3.png")
    pg.keyboard.press("Escape"); pg.wait_for_timeout(700); pg.reload(); pg.wait_for_timeout(700)
    txt=pg.locator(".colb").nth(3).inner_text()
    ok("card tags persist", "Blocked: Needs 4 hr downtime" in txt and "Carousel downtime" in txt and "1/2" in txt)
    ok("attn blocked", "1 blocked" in pg.locator(".attn").inner_text())
    pg.locator(".sub label").filter(has_text="Blocked only").locator("input").check()
    ok("blocked filter", pg.locator(".card").count()==1); pg.locator(".sub label").filter(has_text="Blocked only").locator("input").uncheck()
    pg.locator('.tabs button[data-v="bundles"]').click(); pg.wait_for_timeout(80)
    ok("bundle lists member", pg.locator(".bundle .bm").count()==1)
    pg.screenshot(path=os.path.join(R,"tests/shots/")+"bundles.png")
    pg.locator('.tabs button[data-v="timeline"]').click(); pg.wait_for_timeout(80)
    ok("timeline bars", pg.locator(".tlrow .bar").count()>=2)
    ok("timeline band", pg.locator(".band").count()==1)
    ok("timeline blocked hatched", pg.locator(".bar.blk").count()==1)
    pg.screenshot(path=os.path.join(R,"tests/shots/")+"timeline.png")
    pg.locator('.tabs button[data-v="review"]').click()
    ok("review blocked", "Needs 4 hr downtime" in pg.locator("main").inner_text())
    # unblock clears
    pg.locator('.tabs button[data-v="board"]').click(); pg.wait_for_timeout(450); pg.locator(".colb").nth(3).locator(".card").first.click()
    pg.locator(".drawer .blkh input").uncheck(); ok("unblocked", "Blocked:" not in pg.locator(".colb").nth(3).inner_text())
    pg.keyboard.press("Escape")
    # mobile
    pg.set_viewport_size({"width":390,"height":800}); pg.locator('.tabs button[data-v="mine"]').click()
    ok("mobile no overflow", pg.evaluate("document.documentElement.scrollWidth")<=390)
    pg.screenshot(path=os.path.join(R,"tests/shots/")+"mobile.png")
    # store round trip: what the API holds must match the screen
    pg.wait_for_timeout(800)
    req=urllib.request.Request(F.rstrip("/")+"/api/state",headers={"X-Key":KEY}); st=json.loads(urllib.request.urlopen(req).read())
    ok("store has owner Rick", any(a["ownerId"]==next(p["id"] for p in st["people"] if p["name"]=="Rick Uher") and a["stage"]=="Doing" for a in st["actions"]))
    ok("store has checklist", len(st["checklist_items"])==2 and sum(1 for c in st["checklist_items"] if c["done"])==1)
    ok("store has bundle", len(st["bundles"])==1 and st["bundles"][0]["name"]=="Carousel downtime")
    ok("store soft-deleted merged", not any(a["title"]=="Change out the cylinders" for a in st["actions"]))
    ok("store versions advanced", max(a["version"] for a in st["actions"])>=2)
    # conflict: stale version is refused
    a0=st["actions"][0]; stale=dict(a0); stale["version"]=a0["version"]-1; stale["title"]="stale write"
    r=urllib.request.Request(F.rstrip("/")+"/api/save",data=json.dumps({"rows":[{"table":"actions","row":stale}]}).encode(),headers={"X-Key":KEY,"Content-Type":"application/json"},method="POST")
    try: urllib.request.urlopen(r); code=200
    except urllib.error.HTTPError as e: code=e.code
    ok("stale write refused 409", code==409)
    bad=urllib.request.Request(F.rstrip("/")+"/api/state",headers={"X-Key":"nope"})
    try: urllib.request.urlopen(bad); code=200
    except urllib.error.HTTPError as e: code=e.code
    ok("wrong key 401", code==401)
    ok("no errors", not errs); print(errs)
    b.close()
print("%d of %d checks passed"%(sum(1 for r in res if r[1]),len(res)))
if srv: srv.terminate()
sys.exit(0 if all(r[1] for r in res) else 1)
